AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-openai

  Lamda querying openai API - chat

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaOpenAiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-openai/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          OPENAI_API_KEY:
      Events:
        LambdaOpenAi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /traits
            Method: post
  LambdaOpenAiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda-openai/node_modules
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaOpenAiApi:
    Description: 'API Gateway endpoint URL for Prod stage for Lambda OpenAi function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/traits/'
  LambdaOpenAiFunction:
    Description: 'OpenAi Lambda Function ARN'
    Value: !GetAtt LambdaOpenAiFunction.Arn
  LambdaOpenAiFunctionIamRole:
    Description: 'Implicit IAM Role created for OpenAi function'
    Value: !GetAtt LambdaOpenAiFunctionRole.Arn
